FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libpq-dev gcc netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY ./HttpParser /HttpParser

WORKDIR /HttpParser

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
