"""Remove unique constraint on contest title.

Revision ID: 75345d538d7c
Revises: 
Create Date: 2024-09-06 11:23:18.215095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '75345d538d7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contest_title', table_name='contest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contest_title', 'contest', ['title'], unique=True)
    # ### end Alembic commands ###
