"""Delete redundant unique constraints.

Revision ID: e064a51ce9a6
Revises: 75345d538d7c
Create Date: 2024-09-06 16:49:42.739891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e064a51ce9a6'
down_revision: Union[str, None] = '75345d538d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_code', table_name='team')
    op.drop_constraint('team_name_key', 'team', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('team_name_key', 'team', ['name'])
    op.create_index('ix_team_code', 'team', ['code'], unique=True)
    # ### end Alembic commands ###
