"""Added to SkillWarriorLink

Revision ID: 43e6ebc68bc7
Revises: 530af0ca912f
Create Date: 2024-08-18 11:05:58.566883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43e6ebc68bc7'
down_revision: Union[str, None] = '530af0ca912f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skillwarriorlink', sa.Column('yet_another_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skillwarriorlink', 'yet_another_field')
    # ### end Alembic commands ###
